### ISSUE TITLE
能不能编译一个在windows下可执行的exe文件？

### ISSUE THREAD

**Issue by lukemin** [Sansui233/proxypoolCheck#1]
能不能编译一个在windows下可执行的exe文件？

**Comment by Sansui233** [comment]
我没有windows的电脑无法测试编译的结果，应该会有一些问题。您如果是windows可以自己试着编译一下。

**Comment by SNIPERAKA** [comment]
完全小白，能教教我吗大佬，我想自力更生找节点，天天找人要感觉不太好

**Comment by SNIPERAKA** [comment]
我是为了你注册的，完全看不懂

**Comment by Sansui233** [comment]
> 我是为了你注册的，完全看不懂

完全看不懂说明此项目目前不太适合你。

想自己动手操作你可以先移步原项目[proxypool](https://github.com/sansui233/proxypool)阅读readme和wiki。需要了解linux与服务器并会实际操作，了解计算机网络五层模型的上三层，了解Clash配置文件的写法和作用。

如果只是想用节点的但对计算机系统了解不够的话，没有必要自己部署项目，找人部署好的用就行。

另外issue主要用于项目反馈，并非社交媒体评论区，请勿多次闲聊式回复。

**Comment by lukemin** [comment]
主要是我的vps都是国外的，用来收集可以，但是检测的时候不准，本地懒得安装双系统。

**Comment by Sansui233** [comment]
> 主要是我的vps都是国外的，用来收集可以，但是检测的时候不准，本地懒得安装双系统。

嗯。上面的不是回复你。windows版本需要添加在makefile添加相应的的交叉编译参数，需要了解go的跨平台编译。问题主要是程序对于路径格式没测试，因为我个人用的mac。还有win现在可以直接用WSL。

**Comment by SNIPERAKA** [comment]
谢谢大佬解释

Sansui233 <notifications@github.com> 于 2021年1月25日周一 22:58写道：
