### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by jth445600** [Sansui233/proxypoolCheck#18]
time: missing Location in call to Time.In

**Comment by jth445600** [comment]
time: missing Location in call to Time.In

**Comment by jth445600** [comment]
@Sansui233

**Comment by Sansui233** [comment]
你的运行环境是？

**Comment by jth445600** [comment]
我编译的windows.我自己改了一下,
![image.png](https://i.loli.net/2021/05/31/MSQlTXFx431fweH.png)

改成了
![image.png](https://i.loli.net/2021/05/31/Xel7RSHI21gfpWn.png)

好像是可以用了,

没改之前我的win10可以用,但是其他人不可以用.改完我还没找到人测.

**Comment by jth445600** [comment]
大佬有win系统的话,可以试一下.
https://445600.ml/bin.zip
https://445600.ml/bin2.zip
一个win系统编译的,一个在linux上交叉编译的.

**Comment by Sansui233** [comment]
OK，不过目前没有windows的开发环境没法测试😅 感谢提出
