### ISSUE TITLE
抓取源最多能填几个

### ISSUE THREAD

**Issue by jth445600** [Sansui233/proxypoolCheck#19]
[![1622613050.png](https://z.photos/images/2021/06/02/1622613050.png)](https://z.photos/image/8VnXi)
作者您好，这个位置可以填几个源。我感觉第三个往后就没什么变化了。是最多就支持几个，还是有去除重复。谢谢。

**Comment by jth445600** [comment]
另外就是，这个检测工具，测得并不准确，很多时候能有一半不能用的节点。

**Comment by jth445600** [comment]
@Sansui233

**Comment by Sansui233** [comment]
没有限制。有去重，多了没什么变化大概就是因为去重了。

如果开了速度测试把没速度的过滤掉，这个又会筛掉一大部分。检测部分是使用的clash，并且比clash更严格一些。对于网络上的节点，Clash的检测就常常是显示能用但不能用，我这边本地使用经过检测后Clash显示fail的比例不超过10%，但能用的里面还是有一些实际用不了，不可用的因素太多了，我这边也做不到完全准确。

**Comment by jth445600** [comment]
谢谢回复，我本地在没有开启测速的情况下，4000多节点可以筛出来200多个，大约有100多个可以使用，十几个质量比较好的。这与抓取源和筛选工具都有很大关系。感谢大佬的付出，希望能够继续维护。readme可以加个二维码收款码，大家请你喝杯咖啡呀

**Comment by Sansui233** [comment]
我这边差不多的，源的站点上开了速度筛选，本地400多个检测出来有60多个，基本都是可以用的，总体来说能用的不多。

之后大概是时间有空的时候或者是协议有大更新的再维护了，一半的代码是原仓库抽出来的，速度检测和中转检测的功能也不是我想到的，二维码就不必了，要打赏还是给原作者吧。

**Comment by jth445600** [comment]
我感觉这个节点检查意义不大。同样一个抓取源，我用
```
https://free-spy.445600.ga/clash/proxies?c=CN,HK,TW,JP,SG,KR
```
筛选出来的节点比用工具找出来的要好很多，而且工具把很多好的能用的节点都删掉了
这是我用工具筛选出来的clash节点
```
https://do.445600.cf/conver/sub?target=clash&url=http%3A%2F%2F165.232.154.1%3A8080%2Fv2ray_dd&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Mini_MultiMode.ini&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true
```

这是最上面那个链接转换了一下的clash链接
```
https://do.445600.cf/conver/sub?target=clash&url=https%3A%2F%2Ffree-spy.445600.ga%2Fclash%2Fproxies%3Fc%3DCN%2CHK%2CTW%2CJP%2CSG%2CKR&insert=false&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true
```
你可以打开试一下，差距有点大

**Comment by jth445600** [comment]
很明显这个工具在删除一些不能节点的同时，把很多能用的节点也给删除了。
我用的测试环境是北方100M移动，树莓派3B，没有开启测速，延迟50秒

**Comment by Sansui233** [comment]
直接选国家的不可用数 55/192 
你提供的筛选后文件的不可用数 33/94
我自己筛选的不可用数 10/75

确实会吃掉节点，看来检测的并发数应该改为可调整的，默认的500个并发还是不太行。之前我用朋友的电脑测，同样的环境同样的电脑同样的程序唯一区别只有系统版本号，他运行出来可用节点的结果数是我的1/3……

**Comment by jth445600** [comment]
我觉得这个工具能做到，自动删除“被墙的”“失效的”就可以了.有一些漏网的没事,但是不能把能用的节点删掉.

**Comment by Sansui233** [comment]
OK，会加相应的配置，不过之后的配置参数估计还得自己调整 😅 删除的节点和用Clash检测出不能用的节点基本一致的时候就差不多正常了。

**Comment by Sansui233** [comment]
已更新
