### ISSUE TITLE
建议：关闭TLS证书检查

### ISSUE THREAD

**Issue by wangwang-code** [Sansui233/proxypoolCheck#24]
哎，可惜了个800多可用的节点
作者看看能不能忽略TLS证书检查
```
TLS peer's certificate is not trusted; reason = certificate has expired
```

**Comment by Sansui233** [comment]
程序是没有写 SSL 证书相关的东西的，只有一个简单的 HTTP Server。这是是哪个地方的错误信息？

**Comment by wangwang-code** [comment]
> 程序是没有写 SSL 证书相关的东西的，只有一个简单的 HTTP Server。这是是哪个地方的错误信息？

证书过期
`
2021-06-17 22:48:09Get "https://outseen.tk/clash/proxies?type=vmess": x509: certificate has expired or is not yet valid: current time 2021-06-17T14:48:09Z is after 2021-05-21T08:50:46Z
`

可以通过`InsecureSkipVerify`设置为`true`来忽略证书
例子：
```
tr := &http.Transport{
    TLSClientConfig:    &tls.Config{InsecureSkipVerify: true},
}
client := &http.Client{Transport: tr}
resp, err := client.Get("https://example.com")

if err != nil {
    fmt.Println("error:", err)
    return
}
defer resp.Body.Close()
body, err := ioutil.ReadAll(resp.Body)
fmt.Println(string(body))
```
（实在看不懂源代码

**Comment by wangwang-code** [comment]
为了解决这个问题，彻底删了go和golang，再装go 1.16和golang
（apt有时也不好使

**Comment by Sansui233** [comment]
明白了，抓取的那部分代码不在这个仓库里。我之后改下再测试一下

**Comment by wangwang-code** [comment]
> 明白了，抓取的那部分代码不在这个仓库里。我之后改下再测试一下

@Sansui233 作者大大你理解错了
应该这样说：
从URL地址获取proxypool节点
通过https建立TLS加密连接时，远程服务器（也就是proxypool服务器）的证书过期，导致https建立失败
一整个程序就卡在这里，
人话：与远程服务器建立连接失败，proxypoolCheck无法进行下一步

### 不是HTTP Server的问题 
是http请求的问题
实在看不懂，去看看我提交的Pull requests里看看新添加的代码
### **代码修改的是http包的http Client来跳过TLS证书检查（解决从proxypool服务器get时出现TLS证书过期）**

**Comment by Sansui233** [comment]
啊抱歉，我想的还是 proxypool 的 getter 的抓取方式，忘了这个仓库没有用 proxypool 的 getter，是可以直接改的😅不过 getter 那边看来也能改进一下

**Comment by wangwang-code** [comment]
> 啊抱歉，我想的还是 proxypool 的 getter 的抓取方式，忘了这个仓库没有用 proxypool 的 getter，是可以直接改的😅不过 getter 那边看来也能改进一下

不知道getter 的抓取方式会不会更好，目前的抓取方式真的一言难尽，被墙了连不上就卡住，不测节点
还有些404，网页不存在等等情况，只有有一个网站出问题，就会造成抓取错误没有可用的节点

**Comment by Sansui233** [comment]
> 不知道getter 的抓取方式会不会更好，目前的抓取方式真的一言难尽，被墙了连不上就卡住，不测节点

被墙了连不上就卡住有例子吗？用getter 一样的，墙了网站应该是超时自动失败。

> 还有些404，网页不存在等等情况，只有有一个网站出问题，就会造成抓取错误没有可用的节点

这个是因为现在的代码没写并行。

如果想要达到爬虫的效果还是用[源仓库吧](https://github.com/Sansui233/proxypool/tree/v0.7.3)，现在 proxypool 和 proxypoolCheck 除了前端，能配置的项已经一样了没区别了（很早之前是有区别的）。 proxypoolCheck 这个仓库当时不是为了爬虫而设立的，只是为了本地做检测用，所以原本打算只能填一个源链接，不过有人 pr 了爬取多条链接的代码。但爬取是串行的，所以一个失败后面就没了，而且速度也慢不适合太多源。

**Comment by wangwang-code** [comment]
>被墙了连不上就卡住有例子吗？用getter 一样的，墙了网站应该是超时自动失败。

比如 `连接超时` `等待对方连接重置` `context deadline exceeded (Client.Timeout exceeded while awaiting headers)`
以及一些被污染的域名 `sspool.herokuapp.com`  `proxypool-guest997.herokuapp.com`在中大陆内就污染了
一会打得开，一会找不到网页，抓取（旧的）就因为这地址找不到就出现 `没有可用的节点` 
其他地址不抓取的情况

**可以考虑加个 `状态码` 状态码200才用这个地址抓取出来的 不是200直接丢弃，放弃，继续其他的抓取**
裸抓取很容易被墙 尤其 某移 
**一劳永逸的就是走`http代理`或者`Socks5代理`**
绕过墙来抓取，除了连接时间很长外，基本不会出现 `等待对方连接重置` `找不到网页`（除非跑路了）
这里说`连接时间很长` 意指容易出现 `连接超时` （500+ms）

**Comment by Sansui233** [comment]
上述的问题昨晚已修改，不会出现一个失败导致停止处理后续订阅源的情况了。

**Comment by wangwang-code** [comment]
> 上述的问题昨晚已修改，不会出现一个失败导致停止处理后续订阅源的情况了。

个人比较希望实现通过`http代理`或者`Socks5代理`来抓取订阅源
现在的墙可聪明了

**Comment by Sansui233** [comment]
可以是可以，不过这个不是个爬虫程序，不考虑添加。自用想代理的话环境变量设置个all_proxy即可。

而爬虫的服务器直接部署在国外比较好。爬虫用代理主要是应对反爬虫的情况，而不是gwf。

**Comment by wangwang-code** [comment]
> 可以是可以，不过这个不是个爬虫程序，不考虑添加。自用想代理的话环境变量设置个all_proxy即可。
> 
> 而爬虫的服务器直接部署在国外比较好。爬虫用代理主要是应对反爬虫的情况，而不是gwf。

我的表达视乎有点问题
我想法是通过`http代理`或`Socks5代理`来连接proxypool服务器
裸连proxypool服务器就得过gwf 尤其墙中墙 其他人能打开我就没法打开

**proxypoolCheck通过代理获取proxypool服务器上的的节点**

**Comment by wangwang-code** [comment]
> 自己动手，丰衣足食

我已经改完了
https://github.com/wangwang-code/proxypoolCheck/commit/be97fddc7e1dd21216ea5f664d88aefd0dead636

**Comment by Sansui233** [comment]
我明白你要修改的内容。我的意思是这种在 http 请求中加代理的做法和以下两者任一一个在结果上是一样的
- 程序中设置 os.Setenv("HTTP_PROXY", "http://192.168.0.170:10809")
- 终端中 export http_proxy=http://192.168.0.170:10809

我自身在测试时某些功能时经常使用第二种方法加代理。并且觉得作为检测部分的程序（而非爬虫部分程序），在程序中加上代理的功能不是很有必要。
问题解决了就好👍

**Comment by wangwang-code** [comment]
> 终端中 export http_proxy=http://192.168.0.170:10809

这个我试过，可能是我乌班图系统有点问题，设置了和没设置一样

> 程序中设置 os.Setenv("HTTP_PROXY", "http://192.168.0.170:10809")

`程序` 这里指go 或者说是golang 吗，对于go语言，没有系统性的知识我也不知道如何设置，我只写过java，这方面还得请教您

----------------------------------------------------------

我个人并不喜欢用源码来运行程序 `go run main.go -c /home/dog/config.yaml` 这对于在虚拟机里的Linux来说，消耗太大
二进制（编译好的）运行起来基本秒跑

人话：
**使用编译好的，这条日志出现的快 `The program will run every 30 minutes`**
没编译的得等N久

**Comment by Sansui233** [comment]
> 程序中设置 os.Setenv("HTTP_PROXY", "http://192.168.0.170:10809")

嗯，指 golang 写的代码里设置环境 HTTP_PROXY 环境变量，就是终端中 export http_proxy 的效果。
