### ISSUE TITLE
这是哪里出的错误呢？

### ISSUE THREAD

**Issue by 8413848** [Sansui233/proxypoolCheck#30]
error unmarshaling JSON: json: cannot unmarshal string into 
Go struct field ConfigOptions.server_url of type []string                       
"Config file err. Exit"  
![1111](https://user-images.githubusercontent.com/62091366/132529024-738d323c-96c7-4c93-ad29-8399944ec986.jpg)

**Comment by 8413848** [comment]
貌似，config.yaml 内的某个变量需要加引号？

**Comment by yangyucacaa** [comment]
同问

**Comment by Sansui233** [comment]
> 同问

配置文件格式有误，建议用在线工具等检查和格式化一下yaml
