### ISSUE TITLE
Proxypool + ProxypoolChecker = Openclash 节点测速？

### ISSUE THREAD

**Issue by MaurUppi** [Sansui233/proxypoolCheck#31]
请教一下，这个组合方式 和 Openclash里边如下设置差异在哪里呢？

![7514E31B-3FE3-4391-90B7-4DE3DEEE94E1](https://user-images.githubusercontent.com/47710598/145706467-1bc10129-fdbd-4a0d-91d9-c6f51e40e395.jpeg)

**Comment by Sansui233** [comment]
“测速”这个词有歧义，我倾向于分开说成“延迟测试”和“带宽测试”。Clash 客户端做的延迟测试，proxypoolCheck 做的带宽测试。两个都可以检测节点可用性，用途不一样，proxypool 是生成订阅不代理，open clash 是直接代理不生成订阅。个人不习惯用路由器挂代理，直接用 PC 上的客户端。

另外 proxypool 主要还是个爬虫程序（代理池），订阅源不仅限于 clash 配置文件的格式。
proxypoolCheck 的功能是 proxypool 的一部分，如果 proxypool 运行在国内就没有必要用check。
用 proxypoolCheck 主要是解决放置于国外的 proxypool 大量无效节点卡 Clash 客户端 UI 影响电脑使用的问题。

如果没有爬虫的需求，或者对大量无效节点不在意，用 clash 就可以了。

**Comment by MaurUppi** [comment]
噢，了解了。这样就明白了，对我这些有购买机场服务的来说，Proxy pool及Checker 貌似没有神么意义了。。
或许 https://github.com/thank243/StairUnlocker-Go 对我来说更有现实意义。
谢谢解答
