### ISSUE TITLE
报错Error when fetch

### ISSUE THREAD

**Issue by erbasisan** [Sansui233/proxypoolCheck#34]
Error when fetch
server_url:
  - https://ghproxy.com/raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
这里的链接可以填写订阅的吗，填写以后
Error when fetch https://ghproxy.com/raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml/clash/proxies: no proxy

**Comment by Sansui233** [comment]
上面的可以，下面的挂了。很久没维护了，解析可能会有问题。

**Comment by erbasisan** [comment]
server_url，这个可以填写订阅的链接吗？如果不能订阅链接填写在哪里

**Comment by Sansui233** [comment]
不支持。此项目不是订阅抓取器。

**Comment by erbasisan** [comment]
server_url:
  - https://example.proxypoolserver.com
  - https://example.proxypoolserver.com/clash/proxies?type=vmess
这两个链接填写的是什么格式的

**Comment by erbasisan** [comment]
server_url:
  - https://example.proxypoolserver.com
  - https://example.proxypoolserver.com/clash/proxies?type=vmess
这两个文件有模板吗，大概是什么样子的，原版的proxypool可以抓取各种链接，可以整合到这里吗

**Comment by Sansui233** [comment]
不是文件，是proxypool server的地址。我感觉你可以直接用proxypool，此项目不是订阅抓取器，不考虑整合。要继续开发也是往测速与通用订阅文件生成上做简易gui应用开发，但由于个人精力原因不再维护。

**Comment by erbasisan** [comment]
用网页一键导入到手机clash的时候一直报错
手机clash错误提示：  "get  链接   EOF"


。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
Clash
Clash配置文件: http://127.0.0.1:9099/clash/config 一键导入
Clash proxy-provider：http://127.0.0.1:9099/clash/proxies

点的就是这个一键导入倒入不进到手机的clash

**Comment by erbasisan** [comment]
proxies:
      - {name: github.com/freefq - 日本东京都品川区Linode数据中心 1, server: 139.162.76.223, port: 80, type: vmess, uuid: 37953153-64df-44c8-a966-1f5008c901d6, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /}, udp: true}
      - {name: github.com/freefq - 美国  2, server: do-3.heicloud.cf, port: 443, type: vmess, uuid: a64e6d2e-fdaf-482b-b034-9b50abcfff67, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: do-3.heicloud.cf}}, udp: true}
      - {name: github.com/freefq - 美国  3, server: 137.184.164.233, port: 80, type: vmess, uuid: 5cee90e3-b915-4f1e-bb8d-efadad0c6feb, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /}, udp: true}
      - {name: github.com/freefq - 新加坡OVH 4, server: 51.79.164.146, port: 80, type: vmess, uuid: 2ef64dc8-ca3c-45b8-ad5f-20871452143b, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /}, udp: true}


服务器地址这样是正确的吗

**Comment by erbasisan** [comment]
发现很多测试完虽然显示有很多可用，但是导入到clash里依然有一半测不出速度不能用的

**Comment by Sansui233** [comment]
还是因为很久没维护过了
