### ISSUE TITLE
编译时找不到依赖 https://github.com/Dreamacro/clash/

### ISSUE THREAD

**Issue by AkimioJR** [Sansui233/proxypoolCheck#38]
应该是间接引入的仓库，毕竟在go mod 也没发现
以下是操作流程
```powershell
git clone https://github.com/ssrlive/proxypoolCheck.git
cd proxypoolCheck
go mod download
```

相关报错
```
go: github.com/Dreamacro/clash@v1.8.0: invalid version: git ls-remote -q origin in C:\Users\akimio\go\pkg\mod\cache\vcs\bf7142aa016098484fb7d241c18e60b4335205563dfadf3c257887ec3f836930: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/Dreamacro/clash/' not found
```

**Comment by Sansui233** [comment]
> 应该是间接引入的仓库，毕竟在go mod 也没发现 以下是操作流程
> 
> ```powershell
> git clone https://github.com/ssrlive/proxypoolCheck.git
> cd proxypoolCheck
> go mod download
> ```
> 
> 相关报错
> 
> ```
> go: github.com/Dreamacro/clash@v1.8.0: invalid version: git ls-remote -q origin in C:\Users\akimio\go\pkg\mod\cache\vcs\bf7142aa016098484fb7d241c18e60b4335205563dfadf3c257887ec3f836930: exit status 128:
>         remote: Repository not found.
>         fatal: repository 'https://github.com/Dreamacro/clash/' not found
> ```

太久远了， clash 已经删库了，换个项目吧。
