### ISSUE TITLE
自己编译出来，speedtest无法测速，Clash配置文件无法生成

### ISSUE THREAD

**Issue by nnn149** [Sansui233/proxypoolCheck#8]
speedtest全部速度应该都是0，用speed=1,100筛选不了，speed=0,100等于没筛选。监控网络发现根本没有流量波动。
用你编译的v0.2.3可以正常测速。
clash配置文件生成出来没有节点信息。

**Comment by Sansui233** [comment]
远程的速度目前没法筛选，读取节点时没写入速度信息。

**Comment by nnn149** [comment]
这个测速呀，我用v0.2.3这个测速的时候看网络是有很高的占用的。并且是可以筛选的。
![image](https://user-images.githubusercontent.com/23712868/111756170-e0269000-88d4-11eb-9660-c76f6d39a5a5.png)

下面这个是我编译的，都没有真正在测速，是v0.2.3以后测速代码改了还是咋回事搞不懂
![image](https://user-images.githubusercontent.com/23712868/111756376-182dd300-88d5-11eb-9416-6a82260c9ee1.png)

**Comment by Sansui233** [comment]
测速是一直都在测的，调试发现有测速结果。但v0.2.4没有筛选的问题是mod依赖问题，准备回退一个版本。这个依赖照理说不应该会有问题，计算结果和调试信息完全不同，简言之无论如何都没法开启筛选，我还需要再看。

**Comment by Sansui233** [comment]
最新的commit已修复
